---
abstract: 'Data type validation functions.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Validate-Type
no_index:
  file:
    - t/LocalTest.pm
  package:
    - LocalTest
    - LocalTestParent
provides:
  Data::Validate::Type:
    file: lib/Data/Validate/Type.pm
    version: v1.5.1
requires:
  Carp: '0'
  Data::Dump: '0'
  Exporter: '0'
  Scalar::Util: '1.18'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/Data-Validate-Type/issues
  homepage: https://metacpan.org/release/Data-Validate-Type
  license: http://dev.perl.org/licenses/
  repository: https://github.com/guillaumeaubert/Data-Validate-Type
version: v1.5.1
