---
abstract: 'Public interface encapsulating Params::Util to offer data type validation functions that pass PerlCritic.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Data::Dump: 0
  File::Spec: 0
  Params::Util: 1
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Validate-Type
no_index:
  file:
    - t/LocalTest.pm
provides:
  Data::Validate::Type:
    file: lib/Data/Validate/Type.pm
    version: v1.0.1
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=data-validate-type
  homepage: https://metacpan.org/release/Data-Validate-Type
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://sourceforge.net/p/perldatatype/code
version: v1.0.1
